### ISSUE TITLE
Forks are alright?

### ISSUE THREAD

**Issue by michaelsproul** [ericrasmussen/chromaticleaves#1]
Hi Eric,

Of all the sites listed on the Hakyll examples site, yours was my favourite, so I used it as the basis for my own site. I hope this is alright! I've retained the CC BY-SA license and kept your name in the footer :smile:

Site: http://sproul.io/
Source: https://github.com/michaelsproul/sproul.io

**Comment by ericrasmussen** [comment]
Thanks - your site looks great!  You are welcome to fork/reuse/etc anything with the site layout or the hakyll code with or without attribution. The layout is based on one of the zurb foundation templates with some minor tweaks, so nothing really interesting about the layout except the graphics by http://joelsteudler.com/

**Comment by michaelsproul** [comment]
Great, thanks!
